### ISSUE TITLE
Is faster method to add doubledouble possible within sleef?

### ISSUE THREAD

**Issue by carlkl** [shibatch/sleef#181]
I could be wrong, but it may be useful to take a look at:

https://stackoverflow.com/questions/30573443/optimize-for-fast-multiplication-but-slow-addition-fma-and-doubledouble and http://hal.archives-ouvertes.fr/docs/00/06/33/56/PDF/float-float.pdf for a faster method to add two floatfloat or doubledouble values. If this methods still applies to sleef please ignore my request.

**Comment by shibatch** [comment]
It is not very clear if this method improves the computation speed.

Decker's paper is published in 1971, and in my understanding Knuth later came up with a branchless method for doing the same thing. The branchless version has only one more addition, and usually this is faster. SLEEF's routines are based on the branchless version.

In the stackoverflow page, he says "This definition of Add22 uses 11 additions instead of 20 but it requires some additional code to determine if |ah| >= |bh|," but my implementation of ddadd2_d2_d2_d2 has only 8 additions. Note that my implementation does not try to achieve full DD precision.

Actually I once considered if the Decker's algorithm is faster, and I concluded that the current version is better.

**Comment by carlkl** [comment]
@shibatch, that's a interesting insight into the implemenation details, thanks.
