### ISSUE TITLE
16-bit floating point support

### ISSUE THREAD

**Issue by alexeyr** [shibatch/sleef#320]
It's mentioned in https://github.com/shibatch/sleef/issues/227#issuecomment-432280602 but I wanted to make a separate issue explicitly asking for FP16 support; as mentioned, it's very useful for machine learning.

**Comment by shibatch** [comment]
FP16 is a bit different from other precisions since a single table lookup can implement any function. There are also two kinds of FP16.
Which functions do you need for machine learning? My understanding is that there are many special functions that are only used in machine learning, so I think it is better to implement those functions directly.

**Comment by alexeyr** [comment]
GELU in particular (`0.5 * x * (1 + erf(x / sqrt(2)))`).

**Comment by shibatch** [comment]
I am now looking into this thing, but it seems not so many kinds of hardware support bfloat16 of IEEE 754 half-precision operations. AVX-512 BF16 only does conversion and dot product.
Which specific hardware do you need to be supported?
Only those three operators? Or is it better to create basic operators like add, mul, div, etc?

**Comment by shibatch** [comment]
I made a prototype of table-lookup-based implementation of a vectorized unary function. This implementation lacks rounding and other features.

https://gist.github.com/shibatch/42f82c885f62bc2c063d6500844f937f

Please let me know if things like this is what you need.

**Comment by alexeyr** [comment]
> Which specific hardware do you need to be supported?

We only care about NEON in this particular project. Though it may get shut down before we get to adding FP16 support anyway now :(

**Comment by shibatch** [comment]
It is not likely that I can achieve significant speedup with neon, because it does not have either bfloat16 support or gather operator.

**Comment by alexeyr** [comment]
Unfortunately, now we definitely won't be adding FP16 in any near term. The issue can be closed unless you'd like to keep it open.

**Comment by shibatch** [comment]
Okay. I am now planning to add a FP16 support regardless of what you need.
Thank you for your suggestion.

**Comment by shibatch** [comment]
Hello,

What kind of functionality do you need?
There are two problems in the actual development process: the problem of deciding what the specifications will be and the uncertainty as to whether the implementation of such a function will be fast enough to perform the calculation.
In tlfloat, I implemented fp16, but this is because tlfloat implements all functions with generic precision, and fp16 was implemented as part of that, so in that sense, I implemented the functionality without considering the computation speed.
If we are going to implement fp16 in SLEEF, we need to fully consider whether the implemented function will really be useful for some project and whether the computation speed will be fast enough before proceeding with the implementation, and these are the difficult points in the development process.

**Comment by helloguo** [comment]
> What kind of functionality do you need? 

I'm looking for exp().

> If we are going to implement fp16 in SLEEF, we need to fully consider whether the implemented function will really be useful for some project and whether the computation speed will be fast enough before proceeding with the implementation, and these are the difficult points in the development process.

Makes sense. To run large language models whose data type could be fp16, it's common to convert fp16 to fp32 back and forth, and do some computation with fp32. While fp32 has better accuracy, it would be interesting to see if fp16 computation could give better perf on the CPUs that support fp16.

**Comment by shibatch** [comment]
If it is just for unary functions, the computation would be relatively fast using table lookup. That would be easy to implement and would also help other members understand the problems in implementing non-unary functions.
