### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by shibatch** [shibatch/sleef#46]
One minor bug is found in SLEEF-3.1 and I am planning a minor update. That would be 3.1.1.

https://sourceforge.net/p/sleef/discussion/general/thread/5b641594/

Diana was also mentioning about incrementing version number, though I cannot find the message.

Is it okay to move to three-part version numbering scheme?

**Comment by fpetrogalli-arm** [comment]
I am fine with moving to three-part versioning scheme. @diaena, is it possible to do so in the cmake configuration file?

**Comment by diaena** [comment]
@fpetrogalli-arm Yes.
@shibatch Yes, I remember mentioning versioning as I have some ideas, but I thought it was too early in my work to submit a pull request for that. 

I will take this opportunity to open the discussion. 

I propose that SLEEF uses the Semantic Versioning (http://semver.org/spec/v2.0.0.html) to manage releases. It would adhere to the format: **VERSION_NUMBER=MAJOR.MINOR.PATCH** where each number is incremented following this criteria:

1. MAJOR++ when adding backwards-incompatible changes (like public API changes)
2. MINOR++ when adding functionality which is backwards-compatible
3. PATCH++ when adding minor changes or bug-fixes which are backward-compatible

Because it's very common for open source software projects to use tag versions and annotated list of changes, I propose that SLEEF keeps a change log file (called `CHANGELOG.md`, but some projects call it `NEWS`, `RELEASES` or `HISTORY`) which contains a reverse-chonologically-ordered (latest change first) list of notable changes for each version of the project. The guiding principles for this file are: 

* One entry for every single version / release
* Types of changes should be grouped into sections (e.g. Added, Changed, Removed, Fixed)
* Optional "UNRELEASED" section at the top so that users would see what changes to expect in the future

In order to implement this, I propose we use a `bumpversion.sh` which the user would execute before a new release. This script will do the following: 
* Automatically suggest a MINOR version bump, but allowing the user to opt for MAJOR or PATCH increment.
* Update the CHANGELOG.md file with the new version (+ DATE stamp).
* Commit a new tag "vMAJOR.MINOR.PATCH" to git.

Please let me know what you think or if you have any suggestions. I already have a prototype for the bumpversion.sh script and I could submit a pull request if we agree on this.

**Comment by shibatch** [comment]
Yes, that would be very nice. Is bumpversion.sh the following one?

https://gist.github.com/pete-otaqui/4188238

**Comment by fpetrogalli-arm** [comment]
@diaena: it seems like a great idea to have, please submit your pull request against master (it will be easy to rebase `cmake-transition` against this change as it does not touch any of the work you are making with cmake).

**Comment by diaena** [comment]
It would be similar to that one, but slightly different. I based my script on it, but made a few changes that I would like your thoughts on. 

In short, I do not think it's a good idea to automatically include the gitlog in the changelog file. Git log is full of noise (merge commits, documentation updates etc) and we want to document the noteworthy differences in the evolution of the project. 

The options are:
* Ask user to input the 'content' of the new CHANGELOG.md entry
* Use sophisticated natural language processing and/or recurrent neural network to process the commits message and output a clear, human-readable summary of the changes introduces in the new version.

**Comment by fpetrogalli-arm** [comment]
I wouldn't bother using NLP... I would go for "Ask user to input the 'content' of the new CHANGELOG.md entry", which might reduce to the fact that we don't need the script at all...

**Comment by diaena** [comment]
Well, we don't *need* the script in that sense. The script will make it easier to update the changelog (it will create the headers and add version and timestamp) and it will tag the release on github.

**Comment by fpetrogalli-arm** [comment]
SGTM.
