### ISSUE TITLE
RISC-V architecture missing on https://sleef.org/

### ISSUE THREAD

**Issue by xypron** [shibatch/sleef#524]
With the 3.6 release support for the RISC-V architecture has been added. But it does not show up in the table in https://sleef.org/index.xhtml#environment.

According to toolchains/riscv64-*.cmake clang >= 17 or gcc >= 14 is needed. This should also be mentioned in this section.

Best regards

Heinrich

**Comment by blapie** [comment]
Hello! Thanks for reporting that. It is definitely our omission. However the plan is to remove this table in the near future, since some of these features have retrograded to experimental. But it would make sense for it to contain Risc-V, until actually replaced by the table in README.

By the way, ultimately we would like to switch from html to markdown sources and let github pages render the website.
