### ISSUE TITLE
[cmake] Remaining work

### ISSUE THREAD

**Issue by xoofx** [shibatch/sleef#74]
Just opening an issue to track the remaining work on cmake.
There are a few remaining steps to backport from the old makefile to the `cmake-transition` branch:

- [x] `dft`
- [x] `dft_tester`
- [ ] `gencoef` 

Once this is done, we could remove all the previous makefiles and the `cmake-transition` branch could be merged back on master.
There is also the #71, but not sure it is critical to have it entirely ready on `cmake-transition` for now. It could be done later.

I can help in the process on working on a bit on these steps.

**Comment by shibatch** [comment]
You don't need to include gencoef. This is independent from the other parts.

It is of course okay to work on dft and dft_tester, but I think adding iut building for MSVC has greater priority.
We also need to check if the new build system works on every combination of OS and compiler.

**Comment by fpetrogalli-arm** [comment]
I think we should also add the Intel compiler on Travis to make cmake-transition fully compatible with the original Makefile system.

**Comment by shibatch** [comment]
Does it take time to add aarch64 to Travis?
And aarch32, if possible.

**Comment by shibatch** [comment]
Adding cmake support for dft and dft_tester is almost done.
I am now thinking about removing makefiles.

Linking with libmpfr on Windows is not implemented, and I don't have prospect for this. I think an easy way is to leave makefile for this purpose. This makefile will build iut with Cygwin, and do testing.
Small makefiles will still be needed in order to do cleanup.

There are still a few things to be done.
- AVX512F detection is not working correctly.
- AARCH32 support has to be added
- Intel Compiler support has to be added

**Comment by xoofx** [comment]
Let me quickly check if I can setup libmpfr on Windows

**Comment by xoofx** [comment]
Just an update, I looked at libmpfr on Windows, and it looks like a bit messy in order to get it compile, as it brings 2 unofficial repositories in the dependency + a fork to add cmake compilation integrated.

**Comment by shibatch** [comment]
Okay, thanks.
I will try to write files for building and testing with Cygwin.

**Comment by fpetrogalli-arm** [comment]
Windows testing is supported since https://github.com/shibatch/sleef/pull/128, closing this issue.
