### ISSUE TITLE
sqrtf used instead of xsqrtf_u05?

### ISSUE THREAD

**Issue by xoofx** [shibatch/sleef#75]
hi @shibatch 

I just noticed in a few place in sleefsp.c, here for example:

https://github.com/shibatch/sleef/blob/d9ba2e3f663def82112f879c8257f690916e3c12/src/libm/sleefsp.c#L898-L902

That the function `sqrtf` is used (I believe this could be a c from math.h), instead of using the internal one `xsqrtf_u05`.
Is there any reason for this? Could it use the internal one?

**Comment by shibatch** [comment]
You can use xsqrtf_u05 instead of sqrtf, but it is much slower.
A single instruction like _mm_sqrt_ps is expected to be emitted where the standard sqrtf function is used.
I implemented functions like xsqrtf_u05 since I want to claim that SLEEF implements all FP real functions defined in C99 math.h.

**Comment by xoofx** [comment]
Makes sense, I will map sqrt to the available function on the target CPU then. Thanks

**Comment by xoofx** [comment]
Just a last question about the accuracy of u05. There are a few functions that provide this accuracy. How does it compare to MPFR/regular libm library for instance? Do they provide internally something closer to u05 or u10? (I'm trying to decide if I would use these functions or would just stick with u10 for regular precision)

**Comment by shibatch** [comment]
Just rounding an infinitely precise real number to a floating point number adds 0.5ULP of error. u05 functions are supposed to give results with the least error.

As you know, the precision of calculation by MPFR can be set arbitrary. For u05 functions, the tester set the precision for MPFR calculation to much higher than double precision, and checks if the results exactly match the calculation by SLEEF, bit-by-bit.

On the other hand, u10 functions tolerate 0.5 ULP error in addition to the error caused by rounding (which is 0.5ULP).

The precision of calculation by regular libm library depends on implementation actually. You can see some results of measurements with glibc in the following page.

https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html

**Comment by xoofx** [comment]
amazing, thanks for the pointer
